# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  
config.vm.provider "virtualbox" do |v|
  v.customize ["modifyvm", :id, "--ioapic", "on"]
  v.memory = 8096
  v.cpus = 2
  v.name = "hostname"
end

#config.vm.synced_folder ".", "/vagrant", disabled: true
#config.vm.synced_folder "/vz/", "/opt/"

config.vm.network "public_network", bridge: "qtap1", ip: "ip_addr", :netmask => "255.255.255.248"

config.vm.hostname="node1"

config.vm.provision "fix-no-tty", type: "shell" do |s|
    s.privileged = false
    s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
end

config.vm.provision "shell",
    run: "always",
    inline: "route add default gw default_gw_ip"

config.vm.provision "ansible" do |ansible|
 ansible.playbook = "playbook.yml"
 end

end